//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.14 at 10:34:13 PM CLT 
//


package com.redhat.internal.bpmsuite.client.responses.task;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jboss.examples.response.task package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jboss.examples.response.task
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Task.Name }
     * 
     */
    public Task.Name createTaskName() {
        return new Task.Name();
    }

    /**
     * Create an instance of {@link Task.PeopleAssignments }
     * 
     */
    public Task.PeopleAssignments createTaskPeopleAssignments() {
        return new Task.PeopleAssignments();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link Task.PeopleAssignments.PotentialOwner }
     * 
     */
    public Task.PeopleAssignments.PotentialOwner createTaskPeopleAssignmentsPotentialOwner() {
        return new Task.PeopleAssignments.PotentialOwner();
    }

    /**
     * Create an instance of {@link Task.PeopleAssignments.BusinessAdministrator }
     * 
     */
    public Task.PeopleAssignments.BusinessAdministrator createTaskPeopleAssignmentsBusinessAdministrator() {
        return new Task.PeopleAssignments.BusinessAdministrator();
    }

    /**
     * Create an instance of {@link Task.Subject }
     * 
     */
    public Task.Subject createTaskSubject() {
        return new Task.Subject();
    }

    /**
     * Create an instance of {@link Task.Description }
     * 
     */
    public Task.Description createTaskDescription() {
        return new Task.Description();
    }

    /**
     * Create an instance of {@link Task.JaxbTaskData }
     * 
     */
    public Task.JaxbTaskData createTaskJaxbTaskData() {
        return new Task.JaxbTaskData();
    }

}
