//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.14 at 10:34:13 PM CLT 
//


package com.redhat.internal.bpmsuite.client.responses.task;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="subject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="description">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="people-assignments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="potential-owner">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="business-administrator" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="jaxbTaskData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="previous-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="actual-owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="created-by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="created-on" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="activation-time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="skipable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="work-item-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="process-instance-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="document-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="document-content-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="output-content-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="fault-content-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="parent-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="process-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="process-session-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="deployment-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="deadlines" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="form-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "priority",
    "name",
    "subject",
    "description",
    "peopleAssignments",
    "jaxbTaskData",
    "deadlines",
    "formName"
})
@XmlRootElement(name = "task")
public class Task {

    protected long id;
    protected long priority;
    @XmlElement(required = true)
    protected Task.Name name;
    @XmlElement(required = true)
    protected Task.Subject subject;
    @XmlElement(required = true)
    protected Task.Description description;
    @XmlElement(name = "people-assignments", required = true)
    protected Task.PeopleAssignments peopleAssignments;
    @XmlElement(required = true)
    protected Task.JaxbTaskData jaxbTaskData;
    @XmlElement(required = true)
    protected String deadlines;
    @XmlElement(name = "form-name", required = true)
    protected String formName;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public long getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(long value) {
        this.priority = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Task.Name }
     *     
     */
    public Task.Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Task.Name }
     *     
     */
    public void setName(Task.Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link Task.Subject }
     *     
     */
    public Task.Subject getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Task.Subject }
     *     
     */
    public void setSubject(Task.Subject value) {
        this.subject = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Task.Description }
     *     
     */
    public Task.Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Task.Description }
     *     
     */
    public void setDescription(Task.Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the peopleAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link Task.PeopleAssignments }
     *     
     */
    public Task.PeopleAssignments getPeopleAssignments() {
        return peopleAssignments;
    }

    /**
     * Sets the value of the peopleAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Task.PeopleAssignments }
     *     
     */
    public void setPeopleAssignments(Task.PeopleAssignments value) {
        this.peopleAssignments = value;
    }

    /**
     * Gets the value of the jaxbTaskData property.
     * 
     * @return
     *     possible object is
     *     {@link Task.JaxbTaskData }
     *     
     */
    public Task.JaxbTaskData getJaxbTaskData() {
        return jaxbTaskData;
    }

    /**
     * Sets the value of the jaxbTaskData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Task.JaxbTaskData }
     *     
     */
    public void setJaxbTaskData(Task.JaxbTaskData value) {
        this.jaxbTaskData = value;
    }

    /**
     * Gets the value of the deadlines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadlines() {
        return deadlines;
    }

    /**
     * Sets the value of the deadlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadlines(String value) {
        this.deadlines = value;
    }

    /**
     * Gets the value of the formName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormName() {
        return formName;
    }

    /**
     * Sets the value of the formName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormName(String value) {
        this.formName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "text",
        "lang"
    })
    public static class Description {

        protected long id;
        @XmlElement(required = true)
        protected String text;
        @XmlElement(required = true)
        protected String lang;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="previous-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="actual-owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="created-by" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="created-on" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="activation-time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="skipable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="work-item-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="process-instance-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="document-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="document-content-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="output-content-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="fault-content-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="parent-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="process-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="process-session-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="deployment-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "previousStatus",
        "actualOwner",
        "createdBy",
        "createdOn",
        "activationTime",
        "skipable",
        "workItemId",
        "processInstanceId",
        "documentType",
        "documentContentId",
        "outputContentId",
        "faultContentId",
        "parentId",
        "processId",
        "processSessionId",
        "deploymentId"
    })
    public static class JaxbTaskData {

        @XmlElement(required = true)
        protected String status;
        @XmlElement(name = "previous-status", required = true)
        protected String previousStatus;
        @XmlElement(name = "actual-owner", required = true)
        protected String actualOwner;
        @XmlElement(name = "created-by", required = true)
        protected String createdBy;
        @XmlElement(name = "created-on", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createdOn;
        @XmlElement(name = "activation-time", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar activationTime;
        @XmlElement(required = true)
        protected String skipable;
        @XmlElement(name = "work-item-id")
        protected long workItemId;
        @XmlElement(name = "process-instance-id")
        protected long processInstanceId;
        @XmlElement(name = "document-type", required = true)
        protected String documentType;
        @XmlElement(name = "document-content-id")
        protected long documentContentId;
        @XmlElement(name = "output-content-id")
        protected long outputContentId;
        @XmlElement(name = "fault-content-id")
        protected long faultContentId;
        @XmlElement(name = "parent-id")
        protected long parentId;
        @XmlElement(name = "process-id", required = true)
        protected String processId;
        @XmlElement(name = "process-session-id")
        protected long processSessionId;
        @XmlElement(name = "deployment-id", required = true)
        protected String deploymentId;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the previousStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreviousStatus() {
            return previousStatus;
        }

        /**
         * Sets the value of the previousStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreviousStatus(String value) {
            this.previousStatus = value;
        }

        /**
         * Gets the value of the actualOwner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActualOwner() {
            return actualOwner;
        }

        /**
         * Sets the value of the actualOwner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActualOwner(String value) {
            this.actualOwner = value;
        }

        /**
         * Gets the value of the createdBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreatedBy() {
            return createdBy;
        }

        /**
         * Sets the value of the createdBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreatedBy(String value) {
            this.createdBy = value;
        }

        /**
         * Gets the value of the createdOn property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreatedOn() {
            return createdOn;
        }

        /**
         * Sets the value of the createdOn property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreatedOn(XMLGregorianCalendar value) {
            this.createdOn = value;
        }

        /**
         * Gets the value of the activationTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getActivationTime() {
            return activationTime;
        }

        /**
         * Sets the value of the activationTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setActivationTime(XMLGregorianCalendar value) {
            this.activationTime = value;
        }

        /**
         * Gets the value of the skipable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkipable() {
            return skipable;
        }

        /**
         * Sets the value of the skipable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkipable(String value) {
            this.skipable = value;
        }

        /**
         * Gets the value of the workItemId property.
         * 
         */
        public long getWorkItemId() {
            return workItemId;
        }

        /**
         * Sets the value of the workItemId property.
         * 
         */
        public void setWorkItemId(long value) {
            this.workItemId = value;
        }

        /**
         * Gets the value of the processInstanceId property.
         * 
         */
        public long getProcessInstanceId() {
            return processInstanceId;
        }

        /**
         * Sets the value of the processInstanceId property.
         * 
         */
        public void setProcessInstanceId(long value) {
            this.processInstanceId = value;
        }

        /**
         * Gets the value of the documentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentType() {
            return documentType;
        }

        /**
         * Sets the value of the documentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentType(String value) {
            this.documentType = value;
        }

        /**
         * Gets the value of the documentContentId property.
         * 
         */
        public long getDocumentContentId() {
            return documentContentId;
        }

        /**
         * Sets the value of the documentContentId property.
         * 
         */
        public void setDocumentContentId(long value) {
            this.documentContentId = value;
        }

        /**
         * Gets the value of the outputContentId property.
         * 
         */
        public long getOutputContentId() {
            return outputContentId;
        }

        /**
         * Sets the value of the outputContentId property.
         * 
         */
        public void setOutputContentId(long value) {
            this.outputContentId = value;
        }

        /**
         * Gets the value of the faultContentId property.
         * 
         */
        public long getFaultContentId() {
            return faultContentId;
        }

        /**
         * Sets the value of the faultContentId property.
         * 
         */
        public void setFaultContentId(long value) {
            this.faultContentId = value;
        }

        /**
         * Gets the value of the parentId property.
         * 
         */
        public long getParentId() {
            return parentId;
        }

        /**
         * Sets the value of the parentId property.
         * 
         */
        public void setParentId(long value) {
            this.parentId = value;
        }

        /**
         * Gets the value of the processId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessId() {
            return processId;
        }

        /**
         * Sets the value of the processId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessId(String value) {
            this.processId = value;
        }

        /**
         * Gets the value of the processSessionId property.
         * 
         */
        public long getProcessSessionId() {
            return processSessionId;
        }

        /**
         * Sets the value of the processSessionId property.
         * 
         */
        public void setProcessSessionId(long value) {
            this.processSessionId = value;
        }

        /**
         * Gets the value of the deploymentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeploymentId() {
            return deploymentId;
        }

        /**
         * Sets the value of the deploymentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeploymentId(String value) {
            this.deploymentId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "text",
        "lang"
    })
    public static class Name {

        protected long id;
        @XmlElement(required = true)
        protected String text;
        @XmlElement(required = true)
        protected String lang;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="potential-owner">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="business-administrator" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "potentialOwner",
        "businessAdministrator"
    })
    public static class PeopleAssignments {

        @XmlElement(name = "potential-owner", required = true)
        protected Task.PeopleAssignments.PotentialOwner potentialOwner;
        @XmlElement(name = "business-administrator")
        protected List<Task.PeopleAssignments.BusinessAdministrator> businessAdministrator;

        /**
         * Gets the value of the potentialOwner property.
         * 
         * @return
         *     possible object is
         *     {@link Task.PeopleAssignments.PotentialOwner }
         *     
         */
        public Task.PeopleAssignments.PotentialOwner getPotentialOwner() {
            return potentialOwner;
        }

        /**
         * Sets the value of the potentialOwner property.
         * 
         * @param value
         *     allowed object is
         *     {@link Task.PeopleAssignments.PotentialOwner }
         *     
         */
        public void setPotentialOwner(Task.PeopleAssignments.PotentialOwner value) {
            this.potentialOwner = value;
        }

        /**
         * Gets the value of the businessAdministrator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the businessAdministrator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBusinessAdministrator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Task.PeopleAssignments.BusinessAdministrator }
         * 
         * 
         */
        public List<Task.PeopleAssignments.BusinessAdministrator> getBusinessAdministrator() {
            if (businessAdministrator == null) {
                businessAdministrator = new ArrayList<Task.PeopleAssignments.BusinessAdministrator>();
            }
            return this.businessAdministrator;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "type"
        })
        public static class BusinessAdministrator {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(required = true)
            protected String type;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "type"
        })
        public static class PotentialOwner {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(required = true)
            protected String type;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "text",
        "lang"
    })
    public static class Subject {

        protected long id;
        @XmlElement(required = true)
        protected String text;
        @XmlElement(required = true)
        protected String lang;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

    }

}
